### ISSUE TITLE
package compiling fails on board itself.

### ISSUE THREAD

**Issue by ubombi** [jakogut/uboot-orangepi-rk3399#1]
Could you please release precompiled package for OPi 4B

I'm always getting an 
```ld.bfd: build/rk3399/release/bl31/bl31.elf section `.pmusram' will not fit in region `PMUSRAM'
ld.bfd: region `PMUSRAM' overflowed by 3928 bytes``` during build from the board itself. (on the same OPi 4B with Dedian bootloader and and arch in `/`rootfs )
 Tried with multiple versions of compiller

----
CrossCompiling kinda works (no errors, have no idea if correctly)
```bash
export CROSS_COMPILE=aarch64-none-elf-
export CARCH=aarch64
export CHOST=aarch64-none-elf-gcc
makepkg
```

but then (after following manual) I get
```
find part:uboot OK. first_lba:0x6000
find part:trust OK. first_lba:0x8000
...
Addr: 0x8000 No find trust.img.
LoadTrustBL error:-3
```

**Comment by jakogut** [comment]
Did you try the orangepi4 branch?

**Comment by ubombi** [comment]
yep, forgot about that.
Build with these lines added to PKGBUILD
```
  export CROSS_COMPILE=aarch64-none-elf-
  export ARM_ARCH_MAJOR=0
  export CFLAGS="-march=armv8-a"
  export CXXFLAGS="-march=armv8-a"
```

Than same steps
* `fdisk n p 1 32768 w`; 
* `bsdtar` unpack
* `cp` qemu-static & compiled package
* `dd` both `idbloader.img` and `u-boot.itb` to sdcard (as in `uboot-orangepi4.install` script)

And now, OPi4B just ignore SDCard and boots from internal eMMC storage

**Comment by ubombi** [comment]
btw `PMUSRAM' overflowed by 3928 bytes` I received on `orangepi4` branch.

**Comment by ubombi** [comment]
Update: 
**Old bootloader from eMMC _(android/orangepi distro)_ does not load new uboot with embeded BL31 trust.** 
> * current u-boot with FIT BL31 is not recognised by DDR/loader in eMMC's BSP and u-boot proper form eMMC does not support MBR only GPT :( ... [original comment](https://github.com/armbian/build/pull/1775#issuecomment-591568077)

So, I also flashed `idbloader.img` to internal memory.
After that, SD card started working.
